services:
  db:
    image: postgres:latest
    ports:
      - POSTGRES_DB = postgres
      - POSTGRES_USER = postgres
      - POSTGRES_PASSWORD = 3142
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    restart: always
    network:
      app_pedidos:
    
  web: 
    build: ./Backend/
    volumes:
      - ./Backend:/code
    ports:
      - "8005:8000"
    depends_on:
      - db
    restart: always
    networks:
      app_pedidos:
  
  react:
    build: ./Frontend/
    ports:
      - "3005:3000"
    volumes:
      - "./Frontend/public:/usr/src/app/public"
      - "./Frontend/src:/usr/src/app/src"
    restart: always
    networks:
      app_pedidos:

      