"""empty message

Revision ID: 1200514878db
Revises: 
Create Date: 2021-08-24 08:45:49.595907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1200514878db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('contrasenia', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partner_id')
    )
    op.create_table('pedidoscabecera',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('tarifa', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.partner_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('pedidoslinea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.Column('id_producto', sa.Integer(), nullable=True),
    sa.Column('cabecera_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cabecera_id'], ['pedidoscabecera.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedidoslinea')
    op.drop_table('pedidoscabecera')
    op.drop_table('usuario')
    # ### end Alembic commands ###
