"""empty message

Revision ID: 5c46a84bccaa
Revises: 35943fa6d4f5
Create Date: 2021-08-18 14:46:39.043444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c46a84bccaa'
down_revision = '35943fa6d4f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'pedidoscabecera', ['id'])
    op.add_column('usuario', sa.Column('email', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'email')
    op.drop_constraint(None, 'pedidoscabecera', type_='unique')
    # ### end Alembic commands ###
