"""empty message

Revision ID: 79e9a8572877
Revises: 1200514878db
Create Date: 2021-08-25 16:12:26.681076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79e9a8572877'
down_revision = '1200514878db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'pedidoscabecera', ['id'])
    op.add_column('usuario', sa.Column('campo_odoo', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'campo_odoo')
    op.drop_constraint(None, 'pedidoscabecera', type_='unique')
    # ### end Alembic commands ###
