"""empty message

Revision ID: 7de4a14a353d
Revises: d01c8cf64bc8
Create Date: 2021-08-16 09:36:17.665214

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7de4a14a353d'
down_revision = 'd01c8cf64bc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidoscabecera', sa.Column('id_usuario', sa.Integer(), nullable=True))
    op.drop_constraint('pedidoscabecera_pedido_cabecera_id_fkey', 'pedidoscabecera', type_='foreignkey')
    op.create_foreign_key(None, 'pedidoscabecera', 'usuario', ['id_usuario'], ['id'])
    op.drop_column('pedidoscabecera', 'pedido_cabecera_id')
    op.drop_column('pedidoscabecera', 'estado')
    op.drop_column('pedidoscabecera', 'fecha')
    op.add_column('pedidoslinea', sa.Column('id_producto', sa.String(length=120), nullable=True))
    op.add_column('pedidoslinea', sa.Column('cabecera_id', sa.Integer(), nullable=True))
    op.drop_constraint('pedidoslinea_pedido_id_fkey', 'pedidoslinea', type_='foreignkey')
    op.create_foreign_key(None, 'pedidoslinea', 'pedidoscabecera', ['cabecera_id'], ['id'])
    op.drop_column('pedidoslinea', 'pedido_id')
    op.drop_column('pedidoslinea', 'product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidoslinea', sa.Column('product', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('pedidoslinea', sa.Column('pedido_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pedidoslinea', type_='foreignkey')
    op.create_foreign_key('pedidoslinea_pedido_id_fkey', 'pedidoslinea', 'pedidoscabecera', ['pedido_id'], ['id'])
    op.drop_column('pedidoslinea', 'cabecera_id')
    op.drop_column('pedidoslinea', 'id_producto')
    op.add_column('pedidoscabecera', sa.Column('fecha', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('pedidoscabecera', sa.Column('estado', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pedidoscabecera', sa.Column('pedido_cabecera_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pedidoscabecera', type_='foreignkey')
    op.create_foreign_key('pedidoscabecera_pedido_cabecera_id_fkey', 'pedidoscabecera', 'usuario', ['pedido_cabecera_id'], ['id'])
    op.drop_column('pedidoscabecera', 'id_usuario')
    # ### end Alembic commands ###
