"""empty message

Revision ID: c47901dae1f7
Revises: 
Create Date: 2021-08-06 15:05:02.070893

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c47901dae1f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidoscabecera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('pedido_cabecera_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_cabecera_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidoslinea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.Column('product', sa.String(length=120), nullable=True),
    sa.Column('tarifa', sa.String(length=100), nullable=True),
    sa.Column('fecha', sa.Time(), nullable=True),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidoscabecera.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('pedidos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cantidad', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('product', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('tarifa', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('fecha', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name='pedidos_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pedidos_pkey')
    )
    op.drop_table('pedidoslinea')
    op.drop_table('pedidoscabecera')
    # ### end Alembic commands ###
