"""empty message

Revision ID: d01c8cf64bc8
Revises: c47901dae1f7
Create Date: 2021-08-10 16:51:28.278525

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd01c8cf64bc8'
down_revision = 'c47901dae1f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidoscabecera', sa.Column('tarifa', sa.String(length=100), nullable=True))
    op.drop_column('pedidoslinea', 'fecha')
    op.drop_column('pedidoslinea', 'tarifa')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidoslinea', sa.Column('tarifa', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('pedidoslinea', sa.Column('fecha', postgresql.TIME(), autoincrement=False, nullable=True))
    op.drop_column('pedidoscabecera', 'tarifa')
    # ### end Alembic commands ###
